### PR TITLE
Hello Microverse Project

### PR DESCRIPTION
**Pull request by Tommymarvel**
In this project, I have worked on the hello microverse project with setting up linters correctly, adding HTML and CSS files with a professional readme.

### CODE REVIEW

**Review by ShahierNashaat — CHANGES_REQUESTED** [review]
Hi <STUDENT_MENTION>, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [x] Kindly be noticed that the README file should be descriptive? AKA: Microverse README template should be used.
- [ ] Kindly be noticed that the Pull Request should have a descriptive title telling you what changes are inside.
- [ ] Kindly be noticed that the Pull Request should have a summary describing introduced changes in more detail.
- [x] Kindly be noticed that the .gitignore file should list `test.md` file and `node_modules`.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by tufoinnkuo10 — CHANGES_REQUESTED** [review]
Hi @Tommymarvel 

Great job so far implementing the changes requested by the previous reviewer 😄 . There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
**To Highlight**;

-  linter checks passed ✔️
-  code works well as expected ✔️
-  correct use of the gitignore ✔️
- Correct readme template✔️


#  Required Changes ♻️ 🚧
_Check the comments under the review._
- [ ] please Add a description summary to your pull request.. you can do that by clicking the 3dots and choosing edit. 👇🏾 ;
Screenshot (33)_LI

almost

###  Optional suggestions
- [ optional] please next time do not open a new pull request or close one unless the one you were working on has already been approved by a code reviewer.
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Required Changes ♻️

Hi @Tommymarvel, This is @sja-thedude your code reviewer.

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

200w

 ## Highlights
✔️ Good job so far

 ## Required Changes ♻️
- [ ] As suggested by the previous reviewer, add a descriptive PR description [here](https://github.com/Tommymarvel/Hello-world/pull/3#issue-1247070976). Instead of "Changing colour of the text from red to plum" you can write "In this project, I have worked on the hello microverse project with setting up linters correctly, adding HTML and CSS files with a professional readme." This shows what you have worked on in the project.
- [ ] Also kindly add the PR title as "`Hello Microverse Project`" instead of `fix style.css file`.

https://user-images.githubusercontent.com/70269507/170435007-103f3853-d684-4c7c-8d9c-b76ba897e53f.mov

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by sja-thedude — APPROVED** [review]
## Project Approved 👍 

Hi @Tommymarvel, This is @sja-thedude your code reviewer.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

giphy

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
